### ISSUE TITLE
Unit shader preview not working

### ISSUE THREAD

**Issue by Tankonyako** [QuackCola/ShaderGraphPlus#6]
https://github.com/user-attachments/assets/7f302fdd-c807-450a-93d7-190ad0862997

**Comment by QuackCola** [comment]
Fixed

**Comment by Tankonyako** [comment]
thank you
Maybe not in cobntext, but is it possible to add a preview like in unity?
But I think it could slow down the editor and cause more temp files to be created but that would be so cool
